### ISSUE TITLE
Setup travis CI

### ISSUE THREAD

**Issue by sockeqwe** [OpenConference/OpenConference-android#19]

**Comment by vanniktech** [comment]
Let me do that for you!

**Comment by sockeqwe** [comment]
Thanks ... first builds will fail for sure because there are some problems
with robolectric tests and build flavors I hadn't time to fix yet ...

Niklas Baudy notifications@github.com schrieb am Sa., 18. Juni 2016,
12:12:

**Comment by vanniktech** [comment]
Yeah I know, also got problems when running `./gradlew clean build` locally

**Comment by sockeqwe** [comment]
It's more Crashlytics related, but I will fix it in the next weeks
